### ISSUE TITLE
Histogram calculus error

### ISSUE THREAD

**Issue by miguel-martinr** [miguel-martinr/Pycture#12]
Sometimes 'normalized' histogram values exceed the limit (1)

![image](https://user-images.githubusercontent.com/45132495/136866288-13f948b3-5c97-42b2-80f8-c1997f655cfc.png)

**Comment by Daniel-del-Castillo** [comment]
Solved by ea9e851f552a9ab91bcfbb6c5ea47a3d4f683a2e
